version: '2'
services:
  nomachine:
    privileged:
    - true
    environment:
    - PASSWORD=AliAly032230
    - USER=shakugan
    cap_add:
    - SYS_PTRACE
    shm_size: 128g
    stdin_open: true
    tty: true
    ports:
    - 4000:4000/tcp
